import React, { Component } from "react";
import $ from "jquery";
import "./legal.css";
import { AppTItle, AppURL } from "../../config/config.js";

class legalTerms extends Component {
  componentDidMount() {
    $("#spanHeaderText").text("legal");
  }
  render() {
    let styles = {
      link: {
        maxWidth: "400px",
        padding: "15px"
      }
    };

    $(".backIcon").show();
    $(".backIconMobile").show();
    const appDomain = AppURL;
    const appName = AppTItle;
    return (
      <div className="container-fluid respobsiveMarginTop contactusmaincontent appGradientColor">
        <h3 className="headingTop headingTopMobile appBodyFontColor appBodyFontFamily">
          {" "}
        </h3>
        <div className="legal-content">
          <div className="legal-header">
            <p>{appName}</p>
            <p>{appDomain}</p>
            <p>TERMS OF SERVICE</p>
          </div>
          <div>
            <div>
              <p>
                THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION
                TECHNOLOGY ACT, 2000 AND RULES THERE UNDER AS APPLICABLE AND THE
                AMENDED PROVISIONS PERTAINING TO ELECTRONIC RECORDS IN VARIOUS
                STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT, 2000.
                THIS ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND
                DOES NOT REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.
              </p>
              <p>
                THIS DOCUMENT IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF
                RULE 3 (1) OF THE INFORMATION TECHNOLOGY (INTERMEDIARIES
                GUIDELINES) RULES, 2011 THAT REQUIRE PUBLISHING THE RULES AND
                REGULATIONS, TERMS OF SERVICES, PRIVACY POLICY AND USER
                AGREEMENT FOR ACCESS OR TERMS OF USAGE OF {appDomain}.
              </p>
            </div>
            <div>
              <p>ABOUT THE {appDomain}</p>
              <p>
                Welcome to the {appDomain}, which is operated by Key Disruptors
                Pvt. Ltd. ("{appDomain}" "we," "our," "us") provide a range of
                content hosting and communication services, to allow agency,
                entity and business to provide services (as defined herein) such
                as hosting, connecting and availing other professionals
                rendering professional services in various areas therein by
                availing, making and preparing custom Web Application.
              </p>
              <p>
                {appDomain}/ IS NOT ENGAGED IN THE OCCUPATION OF PROCURING,
                OFFERING, PROMISING, OR ATTEMPTING TO PROCURE EMPLOYMENT OR
                ENGAGEMENTS IN ANY MANNER WHATSOEVER. WE ARE A COMPREHENSIVE B2B
                SERVICE PROVIDED AND ONLY ARE RESPONSIBLE TO PROVIDE AN ACCESS
                OF customized service based Web Application.* for agency,
                business and similar transaction.
              </p>
              <p>
                Our family of websites includes {appDomain}, of the VisionIT
                2020 Conference. Web Application (collectively known as the
                "Site") which offer features, content, functionality and other
                services ("Services").
              </p>
              <p>
                A "Visitor" is someone who accesses and browses through the
                Site. A "Member" is someone who has registered with the Site.
                Valid and accurate completion of the registration process leads
                to "Membership." Visitors and Members are referred to
                collectively as "Users."{" "}
              </p>
              <p>SCOPE</p>
              <p>
                You agree that, by registering on the Site, or by accessing,
                viewing, downloading or otherwise using the Site or Services,
                and/or by clicking "I Accept" during the registration process,
                you are entering into a legally binding agreement with the
                Company, based on the following terms (i) these Terms of Use and
                our Privacy Policy available, which is hereby incorporated by
                reference (together, the "Agreement") and (ii) such other legal
                notices as may be posted on the Site from time to time. The
                legally binding terms of the Agreement set out your rights,
                obligations, and restrictions regarding your use of our Site.{" "}
              </p>
              <p>
                In order to use or purchase certain Services or specific
                portions of the Site, you may be required to download content,
                software, and/or required to agree to additional terms and
                conditions. Unless otherwise expressly set forth in any such
                additional terms and conditions applicable to the specific
                Services or Site feature in which you choose to participate,
                those additional terms are hereby incorporated into this
                Agreement. You agree to abide by such other terms and
                conditions, including, where applicable, representing that you
                are of sufficient legal age to use or participate in such
                service or feature or have registered with the help of a
                guardian (in case of under-age). If there is a conflict between
                these Terms of Use and any additional terms posted for or
                applicable to a specific Service or portion of the Site, the
                additional terms shall control with respect to your use of such
                specific Service or portion of the Site.
              </p>
              <p>
                By becoming a User, you acknowledge that you have read and
                understood the terms and conditions of this Agreement, including
                our Privacy Policy available, and that you agree to be bound by
                all of its provisions.
              </p>
              <p>WHO MAY USE THE SITE:</p>
              <div>
                <p>as an Agency ("Agency");</p>
                <p>
                  as a band or performance troupe of two or more members (a
                  "Group");
                </p>
                <p>
                  as the professional representative (e.g. a talent agent or
                  manager) of a touring or display property such as a car, an
                  animal such as a cat or dog, a Talent, or a Group; or as a
                  casting director; or on behalf of a company or other legal
                  entity such as an agency, management company, casting
                  director, or production company (each, an "Industry
                  Professional Entity")&rsquo; or
                </p>
                <p>
                  Registered or Guest users invited by the said Agency, Group or
                  Industry Professional Entity, which may have a separate
                  agreement with us, you are nevertheless individually bound by
                  this Agreement as an individual Registered or Guest User.
                </p>
              </div>
              <p>
                ELIGIBILITY FOR MEMBERSHIP AND ABILITY TO ACCEPT TERMS OF USE OF
                SERVICE
              </p>
              <p>
                To be eligible for Membership, you must meet the following
                criteria and you represent and warrant that you:
              </p>
              <div>
                <p>
                  are of the age of majority in your country of residence; or
                </p>
                <p>
                  are Agency, a Group, or an Industry Professional Entity (*)
                  meeting the criteria established by us to qualify for
                  membership as set forth in this Agreement or in any legal
                  notice; or
                </p>
                <p>
                  Registered or Guest users invited by the said Agency, Group or
                  Industry Professional Entity, which may have a separate
                  agreement with us, you are nevertheless individually bound by
                  this Agreement as an individual Registered or Guest User
                </p>
                <p>
                  are the Registering Adult (as defined in "Special Note About
                  Minors") registering and maintaining a Membership on behalf of
                  a minor;
                </p>
                <p>
                  are not currently restricted from using the Services or not
                  otherwise prohibited from being a User;
                </p>
                <p>
                  have full power and authority to enter into this Agreement and
                  doing so will not violate any other agreement to which you are
                  a party or any applicable law;
                </p>
                <p>
                  are not a competitor of {appDomain}or are not using the Site
                  for reasons that are in competition with {appDomain};
                </p>
                <p>
                  will respect and not violate any rights of {appDomain},
                  including {appDomain} copyrights, trademark rights, and other
                  intellectual property rights; and
                </p>
                <p>
                  Are solely responsible for any and all equipment, software,
                  and Internet access necessary to use the Site and any
                  associated costs.
                </p>
              </div>
              <p>
                During the Membership registration process, you will be prompted
                to provide personal information that allows us to know who you
                are, such as your full name, age, street address, email address
                and phone number, as well as additional optional information
                that may be required by {appDomain} (collectively, "Registration
                Information").{" "}
              </p>
              <p>By using the Site, you represent and warrant that:</p>
              <p>
                All Registration Information that is submitted by you is
                truthful, accurate, current and complete;
              </p>
              <p>
                You will maintain the accuracy of such Registration Information
                by updating and revising it promptly; and
              </p>
              <p>
                Your use of the Site does not violate any applicable law or
                regulation of the country of which "User" would be the resident
                of.
              </p>
              <p>
                You authorize {appDomain} to make any inquiries, either directly
                or through third parties, that we consider necessary to validate
                your Registration Information. {appDomain} reserves all rights
                to take legal action against anyone who provides inaccurate,
                false or incomplete personal information or is otherwise
                untruthful about their identity, and to suspend or cancel a
                Membership established using such information. Notwithstanding
                the foregoing, you acknowledge that {appDomain} cannot guarantee
                the accuracy of any information submitted by any User of the
                Site, including any identity information about any User.
              </p>
              <p>SPECIAL NOTE ABOUT MINORS</p>
              <p>
                We do not allow individuals or members of Groups who are under
                the age of majority in their country of residence (a "minor") to
                directly establish their own {appDomain}on the Site. All Users
                who are minors may only post {appDomain} on the Site if they are
                represented by an Industry Professional Entity, parent or legal
                guardian who has registered on their behalf and who maintains
                the {appDomain} on their behalf ("Registering Adult"). We
                reserve the right to add special protections, including to track
                and record visits/views, for the profiles and/or Membership
                accounts of Users who are minors for security purposes.
              </p>
              <p>
                Although we cannot absolutely control whether minors gain
                unauthorized access to our Site, {appDomain}, your {appDomain}{" "}
                may be deactivated and your Membership may be terminated without
                warning if we believe that you are a minor in your country of
                residence and we do not have satisfactory proof or assurances
                that your Membership is maintained on your behalf by a
                Registering Adult.
              </p>
              <p>MEMBERSHIP SECURITY AND UNAUTHORIZED USE</p>
              <p>
                You are fully responsible for all activities conducted through
                your Membership and {appDomain}. During the registration
                process, you will also be provided a passkey. You are entirely
                responsible for maintaining the security of your password. You
                agree not to use another Member&rsquo;s account or password at
                any time, not to let an unauthorized third party use your
                membership, and not to disclose your password information to any
                unauthorized third party. You agree to notify {appDomain}{" "}
                immediately in the event of any unauthorized use of your
                Membership or access to your password takes place. Your
                disclosure of your password to any other person is entirely at
                your own risk.
              </p>
              <p>
                Although {appDomain} will not be liable for your losses caused
                by any unauthorized use of your Membership, you may be liable
                for our losses or the losses of others as a result of such
                unauthorized use until such time as you terminate your
                Membership account or prove that your account security was
                compromised due to no fault of your own.
              </p>
              <p>{appDomain} PRIVACY POLICY</p>
              <p>
                Registration Data and certain other information about you is
                subject to our Privacy Policy which is incorporated by reference
                into and made a part of this Terms of Service. By giving or
                making available the Registration Data and such other
                information about yourself to us, you agree and acknowledge that
                we may use or release such information as specified in the
                Privacy Policy, and that you give consent to such use or
                disclosure. For more information, please see our full privacy
                policy at Privacy Policy. You understand that through your use
                of the Service you consent to the collection and use (as set
                forth in the Privacy Policy) of this information and use by{" "}
                {appDomain}and its affiliates.
              </p>
              <p>COPYRIGHT, TRADEMARKS AND INTELLECTUAL PROPERTY RIGHTS</p>
              <p>
                The trademarks, logos, and service marks, including but not
                limited to *{appDomain} and other names, logos, and icons
                identifying products and services (collectively, "Trademarks")
                displayed on the Site, are registered and unregistered
                Trademarks of {appDomain}, its affiliates, suppliers or others.
                Certain portions of the Site are identified as being the subject
                of a specific copyright held by an entity other than {appDomain}{" "}
                and as such, may not be copied without the permission of the
                holder of the copyright {appDomain} hereby authorizes you to
                copy the Materials published on this Site exclusively for
                non-commercial use by "User" personally or within your
                organization provided you retain all copyright and other
                proprietary notices contained in the Materials and you do not
                modify the Materials. No other use of the Materials is
                authorized. In consideration of this authorization, you agree
                that any copy of the Materials (or any portion of the Materials)
                that you make shall retain all copyright and other proprietary
                notices contained herein or therein. You may not copy or display
                for redistribution to third parties or for commercial purposes
                any portion of the Materials. The services, technology, and/or
                processes described in this Site may be the subject of
                Intellectual Property Rights, Trade Secrets etc. and is reserved
                by {appDomain} or any other third parties. Nothing contained
                herein shall be construed as conferring to you in any manner,
                whether by implication, estoppel or otherwise, any license,
                title or ownership of or to any intellectual property right of{" "}
                {appDomain} or any third party whatsoever.
              </p>
              <p>MEMBER CONDUCT</p>
              <p>
                You understand and acknowledge that all information, data, text,
                software, music, sound, photographs, graphics, video, messages
                or other materials ("Content"), whether publicly posted or
                privately transmitted, are the sole responsibility of the person
                from which such Content originated. This means that you the User
                and, not {appDomain} are entirely responsible for all Content
                that you upload, post, email or otherwise transmit via the
                Service at all given times. {appDomain} does not control the
                Content posted via the Service and as such, cannot and does not
                guarantee the accuracy, integrity or quality of such Content.
                You understand that by using the Service, you may be exposed to
                Content that is offensive, indecent or objectionable. Under no
                circumstances will we or our licensors, suppliers, vendors,
                parent, holding, subsidiary or related companies, affiliates,
                officers, agents or employees, as the case may be liable in any
                way for any Content, including, but not limited to, any exposure
                to offensive, indecent or objectionable Content, any errors or
                omissions in any Content, or for any loss or damage of any kind
                incurred as a result of the use of any Content posted, emailed
                or otherwise transmitted via the Service and {appDomain} at all
                given times reserves its right in equity and law to initiate
                prosecution or help any law or governmental agency in such
                investigation at your cost, risk and peril.
              </p>
              <p>OTHER WEBSITES</p>
              <p>
                When you are on {appDomain} and are asked for personal
                information by {appDomain}, you are sharing that information
                with {appDomain} only. However, Material on {appDomain} may link
                to independently run websites outside of the {appDomain} domain.{" "}
                {appDomain} is not responsible for the privacy practices or
                content of such websites. We encourage you to read the privacy
                policies of any websites you visit from this website as users
                and other members may be able to access certain information that
                you provide to them (e.g. your e-mail address and content that
                you post on the blog). {appDomain} is not in a position to
                monitor or control any particular user's or community member's
                use of that content.
              </p>
              <p>YOU AGREE TO NOT USE THE SERVICE TO:</p>
              <p>
                Upload, post, email or otherwise transmit any Content that is
                unlawful, harmful, threatening, abusive, harassing, tortious,
                defamatory, vulgar, obscene, libellous, invasive of another's
                privacy, hateful, or racially, ethnically or otherwise
                objectionable or contrary to public interest, public order or
                national harmony in all relevant jurisdictions;
              </p>
              <p>Harm minors in any way;</p>
              <p>
                Impersonate, or falsely state or otherwise misrepresent your
                affiliation with, any person or entity, including, but not
                limited to, a *{appDomain} official, forum leader, guide or
                host;
              </p>
              <p>
                Forge headers or otherwise manipulate identifying information in
                order to disguise and/or with the effect of disguising the
                origin of any Content transmitted through the Service;
              </p>
              <p>
                Upload, post, email or otherwise transmit any Content that you
                do not have a right to transmit under any law or under
                contractual or fiduciary relationships (such as inside
                information, proprietary and confidential information learned or
                disclosed as part of employment relationships or under
                non-disclosure agreements);
              </p>
              <p>
                Upload, post, email or otherwise transmit any Content that
                infringes any patent, trademark, trade secret, copyright or
                other proprietary rights ("Rights") of any party;
              </p>
              <p>
                Upload, post, email or otherwise transmit any unsolicited or
                unauthorized advertising, promotional materials, "junk mail",
                "spam", "chain letters", "pyramid schemes" or any other form of
                solicitation, except in those areas that are designated for such
                purpose;
              </p>
              <p>
                Upload, post, email or otherwise make available or transmit any
                material that contains software viruses or any other computer
                code, files or programs designed to interrupt, destroy or limit
                the functionality of any computer software or hardware or
                telecommunications equipment;
              </p>
              <p>
                Disrupt the normal flow of dialogue, cause a screen to "scroll"
                faster than other users of the Service are able to type, or
                otherwise act in a manner that negatively affects other
                users&rsquo; ability to engage in real time exchanges or to
                utilize the service on an "AS IS" basis as provided by us;
              </p>
              <p>
                Interfere with or disrupt the Service or servers or networks
                connected to the Service, or disobey any requirements,
                procedures, policies or regulations of networks connected to the
                Service;
              </p>
              <p>
                Intentionally or unintentionally violate any applicable local,
                state, national or international law, including, but not limited
                to, regulations promulgated by the Information Technology Act,
                2000 as amended to date, The Information Technology
                (Intermediaries Guidelines) Rules, 2011, The Indecent
                Representation Of Women (Prohibition) Act, 1986, Indian
                Securities Exchange Control and other regulatory authorities ,
                any rules of any Indian securities exchange and any regulations
                having the force of law;
              </p>
              <p>
                "Cyber Stalk" or otherwise harass another; Also, Cyber Stalking
                here would have the same meaning and understanding as Stalking
                as per the General Clauses Act,1897, Indian Penal Code, 1860 and
                The Information Technology Act, 2000 as amended till date.
              </p>
              <p>
                Commit any fraudulent or unlawful act, whether in relation to
                any third-party provider of products and services on the Service
                or otherwise punishable under Indian Penal Code, 1860 or The
                Narcotic Drugs and Psychotropic Substances Act, 1985.
              </p>
              <p>
                Collect or store personal data about any other users in
                connection with the prohibited conduct and activities set forth
                in the present agreement.
              </p>
              <p>
                You acknowledge and clearly understand that {appDomain} cannot
                and does not pre-screen Content, but that {appDomain} and its
                designees shall have the right (but not the obligation) in our
                sole discretion to refuse or move any Content that is available
                via the Service. Without limiting the foregoing, {appDomain} and
                its designees shall have the right to remove any Content that we
                believe in good faith violates the Terms of Service or that has
                been alleged to infringe any intellectual property or against
                the sovereignty of the nation or that is otherwise objectionable
                in our sole opinion, without being liable to you in any way for
                any loss or damage arising from such removal. You agree that you
                will evaluate, and bear all risks associated with, the use of
                any Content, including any reliance on the accuracy,
                completeness, or usefulness of such Content. In this regard, you
                acknowledge that you may not rely on any Content created by{" "}
                {appDomain} or submitted to {appDomain}, including without
                limitation information in {appDomain} Message Boards,{" "}
                {appDomain}Groups, and in all other parts of the Service.
              </p>
              <p>
                You acknowledge and agree that {appDomain} may preserve Content
                and may also disclose Content if required to do so by law of the
                land or in the good faith belief that such preservation or
                disclosure is reasonably necessary to:
              </p>
              <p>
                Comply with the legal process of the land including but not
                limiting to Court Orders and Injunctions;
              </p>
              <p>Enforce the Terms of Service;</p>
              <p>
                Respond to claims that any Content violates the rights of
                third-parties;
              </p>
              <p>Respond to your requests for customer service; or</p>
              <p>
                Protect the rights, property, or personal safety of {appDomain},
                its users and the public.
              </p>
              <p>
                You understand that the technical processing and transmission of
                the Service, including your Content, may involve
              </p>
              <p>Transmissions over various networks; and</p>
              <p>
                Changes to conform and adapt to technical requirements of
                connecting networks or devices
              </p>
              <p>
                Where any part of the Service involves or is provided by us in
                conjunction with a third party, you agree to comply with any
                notices, instructions or directives given by such third party in
                relation to such part of the Service, including your access to
                or use thereof.
              </p>
              <p>PREVENTING AND REPORTING ABUSE</p>
              <p>
                You agree that {appDomain} may take whatever steps it deems
                necessary to abridge, or prevent behaviour of any kind on the
                Site that violates this Agreement in {appDomain} sole
                discretion, without notice to you.
              </p>
              <p>
                {appDomain} has a zero-tolerance policy against any form of
                pornography, and will terminate and report to the appropriate
                authorities any User who publishes or distributes child
                pornography.
              </p>
              <p>
                You can report any violations of the User Code of Conduct or
                other abuse on the Site by emailing hello@thekeysolution.com.
              </p>
              <p>
                SPECIAL ADMONITIONS FOR INTERNATIONAL USE AND EXPORT AND IMPORT
                COMPLIANCE
              </p>
              <p>
                Recognizing the global nature of the Internet, you agree to
                comply with all local rules regarding online conduct and
                acceptable Content. Use of the {appDomain} Services and
                transfer, posting and uploading of software, technology, and
                other technical data via the {appDomain} Services may be subject
                to the export and import laws of the India, United States,
                Singapore and other countries.
              </p>
              <p>
                CONTENT SUBMITTED OR MADE AVAILABLE FOR INCLUSION ON THE SERVICE
              </p>
              <p>
                {appDomain} does not claim ownership of Content you submit or
                make available for inclusion on the Service. However, with
                respect to Content you submit or make available for inclusion on
                publicly accessible areas of the Service, you grant {appDomain}{" "}
                the following worldwide, royalty-free and non-exclusive
                license(s), as applicable:
              </p>
              <div>
                <p>
                  With respect to Content you submit or make available for
                  inclusion on publicly accessible areas of {appDomain} Groups,
                  the license to use, distribute, reproduce, modify, adapt,
                  publicly perform and publicly display such Content on the
                  Service solely for the purposes of providing and promoting the
                  specific {appDomain} Group to which such Content was submitted
                  or made available. This license exists only for as long as you
                  elect to continue to include such Content on the Service and
                  will terminate at the time you remove or {appDomain}removes
                  such Content from the Service.
                </p>
                <p>
                  With respect to photos, graphics, audio or video you submit or
                  make available for inclusion on publicly accessible areas of
                  the Service other than {appDomain} Groups, the license to use,
                  distribute, reproduce, modify, adapt, publicly perform and
                  publicly display such Content on the Service solely for the
                  purpose for which such Content was submitted or made
                  available. This license exists only for as long as you elect
                  to continue to include such Content on the Service and will
                  terminate at the time you remove or {appDomain} removes such
                  Content from the Service.
                </p>
                <p>
                  With respect to Content other than photos, graphics, audio or
                  video you submit or make available for inclusion on publicly
                  accessible areas of the Service other than {appDomain} Groups,
                  the perpetual, irrevocable and fully sub-licensable license to
                  use, distribute, reproduce, modify, adapt, publish, translate,
                  publicly perform and publicly display such Content (in whole
                  or in part) and to incorporate such Content into other works
                  in any format or medium now known or later developed.
                </p>
              </div>
              <p>CONTRIBUTIONS TO {appDomain}</p>
              <p>
                By submitting ideas, suggestions, documents, and/or proposals
                ("Contributions") to {appDomain} through its suggestion or
                feedback App/Web Pages, you acknowledge and agree that:
              </p>
              <div>
                <p>
                  Your Contributions do not contain confidential or proprietary
                  information;
                </p>
                <p>
                  {appDomain} is not under any obligation of confidentiality,
                  express or implied, with respect to the Contributions;
                </p>
                <p>
                  {appDomain} shall be entitled to use or disclose (or choose
                  not to use or disclose) such Contributions for any purpose, in
                  any way, in any media worldwide;
                </p>
                <p>
                  {appDomain} may have something similar to the Contributions
                  already under consideration or in development;
                </p>
                <p>
                  Your Contributions automatically become the property of{" "}
                  {appDomain} without any obligation of {appDomain}; and
                </p>
                <p>
                  You are not entitled to any compensation or reimbursement of
                  any kind from {appDomain} under any circumstances.
                </p>
              </div>
              <p>INDEMNITY</p>
              <p>
                You agree to indemnify and hold {appDomain}, and our licensors,
                suppliers, vendors, parent, subsidiaries and related companies,
                affiliates, officers, agents, co-branders or other partners, and
                employees, harmless from any claim or demand, including
                reasonable legal fees, made by any third party due to or arising
                out of Content you submit, post to or transmit or make available
                through the Service, your use of the Service, your connection to
                the Service, your use of any Channels, your violation of the
                Terms of Service, or your violation of any rights of any other
                persons, or your breach of any applicable law.
              </p>
              <p>NO RESALE OF SERVICE</p>
              <p>
                You agree not to reproduce, duplicate, copy, sell, resell or
                exploit for any commercial purposes, any portion of the Service,
                use of the Service, or access to the Service; unless it&rsquo;s
                done with written permission of {appDomain}.
              </p>
              <p>GENERAL PRACTICES REGARDING USE AND STORAGE</p>
              <p>
                You acknowledge that {appDomain} may, in its sole discretion,
                establish general practices and limits concerning use of the
                Service, including without limitation the maximum number of days
                that email messages, message board postings or other uploaded
                Content will be retained by the Service, the maximum number of
                email messages or any other messages that may be sent from or
                received by an account on the Service or transmitted through the
                Service, the maximum size of any email message that may be sent
                from or received by an account on the Service, the maximum disk
                space that will be allotted on {appDomain} servers on your
                behalf, and the maximum number of times (and the maximum
                duration for which) you may access the Service in a given period
                of time. In particular, but without limiting the foregoing, by
                using the Service, you consent to our adoption of the practices,
                set forth in relation to your use of the Service. You agree that{" "}
                {appDomain} has no responsibility or liability for the deletion
                or failure to store any messages and other communications or
                other Content maintained or transmitted by the Service. You
                acknowledge that {appDomain} the right to log off accounts that
                are inactive for an extended period of time. You further
                acknowledge that {appDomain} reserves the right to change these
                general practices and limits at any time, in its sole
                discretion, with or without notice. You further acknowledge that
                we reserve the right to modify these general practices and
                limits at any time, in our sole discretion, with or without
                notice, and you agree that your continued use of the Service
                after such modification will constitute your acceptance of an
                agreement to be bound by the modified general practices and
                limits.
              </p>
              <p>MODIFICATIONS TO SERVICE</p>
              <p>
                {appDomain} reserves the right at any time and from time to time
                to modify or discontinue, temporarily or permanently, the
                Service (or any part thereof) with or without notice, for any
                reason whatsoever, whether generally or limited to you only You
                agree that {appDomain} shall not be liable in any way to you or
                to any third party for any modification, suspension or
                discontinuance of the Service.
              </p>
              <p>TERMINATION</p>
              <p>
                You agree that {appDomain}, in its sole discretion, may
                terminate your password, account (or any part thereof) or use of
                the Service, and remove and discard any Content within the
                Service, for any reason, including, without limitation, for lack
                of use or if {appDomain} in its sole opinion, believes that you
                have violated or acted inconsistently with the letter or spirit
                of the Terms of Service or that you are a repeat infringer of
                Intellectual Property Rights. {appDomain} may also in its sole
                discretion and at any time discontinue providing the Service, or
                any part thereof, with or without notice, whether for selected
                or all Channels. You agree that any termination of your access
                to the Service under any provision of this Terms of Service may
                be effected without prior notice, and acknowledge and agree that{" "}
                {appDomain} may immediately deactivate or delete your account
                and all related information and files in your account and/or bar
                any further access to such files or the Service. Further, you
                agree that {appDomain} shall not be liable to you or any
                third-party for any termination of your access to the Service.
              </p>
              <p>DEALINGS WITH THIRD PARTIES</p>
              <p>
                The Service may also include access to products and services of
                independent third parties either directly or via links to sites
                operated by such third parties. Where these products and
                services of third parties form part of the Service, we will
                endeavour, but are not obliged to, indicate that these products
                and services are provided by third parties. In all cases, your
                correspondence or business dealings with, or participation in
                promotions of, other parties found on or through the Service
                (including without limitation providers of products and
                services, advertisers and other users of the Service), including
                payment and delivery of related goods or services, and any other
                terms, conditions, warranties or representations associated with
                such dealings, are solely between you and such third party, even
                where it is in relation to any products or services that are
                co-branded with us which may include our trademarks. You agree
                that we shall not be responsible or liable in any way for any
                loss or damage of any sort incurred as the result of any such
                dealings with any third parties, as the result of the presence
                of such third parties on the Service, or as the result of the
                use of the Service in any way by such third parties.
              </p>
              <p>LINKS</p>
              <p>
                The Service may provide, or third parties may provide, links to
                other World Wide Web or other online electronic sites or
                resources. You acknowledge that {appDomain} has no control over
                such sites and resources, you acknowledge and agree that{" "}
                {appDomain} is not responsible for the availability of such
                external sites or resources, and does not endorse and is not
                responsible or liable for any Content, advertising, products, or
                other materials on or available from such sites or resources.
                You further acknowledge and agree that {appDomain} shall not be
                responsible or liable, in any manner whatsoever, for any damage
                or loss caused or alleged to be caused by or in connection with
                use of or reliance on any such Content, goods or services
                available on or through any such site or resource.
              </p>
              <p>{appDomain} INTELLECTUAL PROPERTY RIGHTS</p>
              <p>
                You acknowledge and agree that the Service and any necessary
                software used in connection with the Service ("Software")
                contain proprietary and confidential information that is
                protected by applicable intellectual property and other laws.
                You further acknowledge and agree that Content contained in
                sponsor advertisements or information presented to you through
                the Service or advertisers is protected by copyrights,
                trademarks, service marks, patents or other proprietary rights
                and laws. Except as expressly authorized by us or advertisers,
                you agree not to modify, adapt, rent, lease, loan, sell,
                distribute or create derivative works based on the Service, the
                Software or the Content (excluding Content owned by you), in
                whole or in part.
              </p>
              <p>DISCLAIMER OF WARRANTIES</p>
              <p>You expressly understand and agree that:</p>
              <p>
                You&rsquo;re accessing or use of the service is at your sole
                risk. The service is provided on an "AS IS" and "AS AVAILABLE"
                basis. We and our licensors, suppliers, vendors, parent,
                holding, subsidiary and related companies, affiliates, officers,
                agents and employees expressly disclaim all warranties of any
                kind, whether express or implied, including, but not limited to
                the implied warranties of merchantability, fitness for a
                particular purpose and non-infringement.
              </p>
              <p>
                2. {appDomain} and its licensors, suppliers, vendors, parent,
                holding, subsidiary and related companies, affiliates, officers,
                agents and employees make no warranty that
              </p>
              <p>The service will meet your requirements,</p>
              <p>
                The service will be uninterrupted, timely, secure, or
                error-free,
              </p>
              <p>
                The service will be accessible at any time or at all times via
                the channel selected or used by you,
              </p>
              <p>
                The information, content or advertisements (collectively, the
                "materials") contained on, distributed through, or linked,
                downloaded or accessed from or through the service, or the
                results that may be obtained from the use of the service, will
                be accurate or reliable,
              </p>
              <p>
                The quality of any products, services, information, or other
                items displayed, purchased or obtained by you through or in
                connection with the service ("the products") will meet your
                expectations,
              </p>
              <p>Any errors in the software will be corrected.</p>
              <p>
                Any material downloaded or otherwise obtained through the use of
                the service is done at your own discretion and risk and that you
                will be solely responsible for any damage to your computer
                system, mobile telephone or other access device or loss of data
                that results from the download of any such material.
              </p>
              <p>
                Any reliance upon or use of any materials shall be at your own
                discretion and risk. We reserve the right, in our sole
                discretion and without any obligation, to make any improvements
                to or correct any error or omissions in any part of the service
                or materials. The materials are provided or made available by us
                on an "AS IS" basis and we expressly disclaim any and all
                warranties of merchantability and fitness for a particular
                purpose, with respect to any of the materials or the products.
              </p>
              <p>
                No advice or information, whether oral or written, obtained by
                you from {appDomain} or its licensors, suppliers, vendors,
                parent, holding, subsidiary and related companies, affiliates,
                officers, agents and employees or through or from the service
                shall create any warranty not expressly stated in the Terms of
                Service.
              </p>
              <p>LIMITATION OF LIABILITY</p>
              <p>
                You expressly understand and agree that we and our licensors,
                suppliers, vendors, parent, holding, subsidiary and related
                companies, affiliates, officers, agents and employees shall not
                be liable for any direct, indirect, incidental, special,
                consequential or exemplary damages, including but not limited
                to, damages for loss of profits, goodwill, use, data or other
                intangible losses (even if we or our licensors, suppliers,
                vendors, parent, holding, subsidiary or related company,
                affiliate, officer, agent or employee, as the case may be, have
                been advised of the possibility of such damages), resulting
                from:
              </p>
              <p>The service, the materials and the products;</p>
              <p>The use or the inability to use the service;</p>
              <p>
                The cost of procurement of substitute goods and services
                resulting from any goods, data, information or services
                purchased or obtained or messages received or transactions
                entered into through or from the service;
              </p>
              <p>
                Unauthorized access to or alteration of your transmissions or
                data;
              </p>
              <p>Statements or conduct of any third party on the service;</p>
              <p>
                Any goods or services disposed of or messages sent or received
                using the service; or
              </p>
              <p>
                Any other matter relating to the service, the materials or the
                products.
              </p>
              <p>EXCLUSIONS AND LIMITATIONS</p>
              <p>
                You acknowledge that the disclaimers and exclusions of liability
                set forth in the above sections and represent a fair and
                reasonable allocation of the risks and benefits of the agreement
                between you the User and {appDomain}, taking all relevant
                factors into consideration, including without limitation the
                value of the consideration provided by you to us and the
                availability and costs of insurance with respect to the said
                risks. You the User further agree that these disclaimers and
                limitations shall be enforceable to the fullest extent permitted
                by applicable law.
              </p>
              <p>NO THIRD-PARTY BENEFICIARIES</p>
              <p>
                You agree that, except as otherwise expressly provided in this
                Terms of Services, there shall be no third-party beneficiaries
                to this agreement.
              </p>
              <p>NOTICE</p>
              <p>
                Notices to you may be made via either email or regular mail. The
                service may also provide notices of changes to the Terms of
                Services or other matters by displaying notices or links to
                notices to you generally on the service. You agree that such
                notices by email or regular mail, and such display of notices or
                links to notices to you generally on the Service, will
                constitute sufficient and adequate notice to you of the matters
                contained therein.
              </p>
              <p>
                NOTICE AND PROCEDURE FOR MAKING CLAIMS OF COPYRIGHT OR
                INTELLECTUAL PROPERTY INFRINGEMENT
              </p>
              <p>
                {appDomain} respects The Intellectual Property of others, and we
                ask our users to do the same. If you believe that your work has
                been copied in a way that constitutes copyright infringement,
                please provide {appDomain} 's Support Staff the following
                information:
              </p>
              <p>
                An electronic or physical signature of the person authorized to
                act on behalf of the owner of the copyright interest.
              </p>
              <p>
                A description of the copyrighted work that you claim has been
                infringed;
              </p>
              <p>
                A description of where the material that you claim is infringing
                is located on the site;
              </p>
              <p>Your address, telephone number, and email address;</p>
              <p>
                A statement by you that you have a good faith belief that the
                disputed use is not authorized by the copyright owner, its
                agent, or the law.
              </p>
              <p>
                A statement by you, made under penalty of perjury as per the
                Indian Penal Code, 1860, that the above information in your
                Notice is accurate and that you are the copyright owner or
                authorized to act on the copyright owner's behalf so as to
                safeguards of {appDomain} falling under the Penalties of the law
                of the land subjected but not limited to the Patents Act, 1970,
                Trademarks Act, 1999, Copyright Act, 1957, Design Act, 2000 and
                other acts applicable.
              </p>
              <p>GENERAL INFORMATION</p>
              <p>
                Entire Agreement. The Terms of Service constitutes the entire
                agreement between User and {appDomain} and govern your use of
                the Service, superseding any prior understandings and agreements
                between User and {appDomain} and any previous statements or
                representations from either party to the other party. The Terms
                of Service do not apply to any affiliate services, third-party
                content or third-party software that does not or cannot
                reasonably be deemed to form part of the Service which may be
                provided to you by our licensors, suppliers, vendors, parent,
                holding, subsidiary or related companies, other affiliates or
                other third parties, which may be subject to additional terms
                and conditions imposed by that party. You also may be subject to
                additional terms and conditions that may apply when you use
                affiliate services, third-party content or third-party software.
              </p>
              <p>
                Governing Law and Jurisdiction. The Terms of Service and the
                relationship between User and {appDomain} shall be governed by
                the laws of India without regard to its conflict of law
                provisions. User and {appDomain} agree to submit to the personal
                and exclusive jurisdiction of the courts located at New Delhi,
                India.
              </p>
              <p>
                Arbitration. If any dispute arises between User and {appDomain}{" "}
                during your use of the App/Website or thereafter, in connection
                with the validity, interpretation, implementation or alleged
                breach of any provision of the User Agreement, Terms of Services
                or the documents they incorporate by reference, the dispute
                shall be referred to a sole Arbitrator who shall be an
                independent and neutral third party identified by {appDomain}.
                The place of arbitration shall be at New Delhi. The Arbitration
                &amp; Conciliation Act, 1996, shall govern the arbitration
                proceedings. The arbitration proceedings shall be in the English
                language.
              </p>
              <p>
                Waiver and Severability of Terms. The failure of {appDomain} to
                exercise or enforce any right or provision of the Terms of
                Service shall not constitute a waiver of such right or
                provision. If any provision of the Terms of Service is found by
                a court of competent jurisdiction to be invalid, the parties
                nevertheless agree that the court should endeavour to give
                effect to the parties&rsquo; intentions as reflected in the
                provision, and the other provisions of the Terms of Service
                remain in full force and effect.
              </p>
              <p>
                No Right of Survivorship and Non-Transferability. You agree that
                your {appDomain} account is non-transferable and any rights to
                your {appDomain} ID or contents within your account terminate
                upon your death. Upon receipt of a copy of a death certificate,
                your account may be terminated and all contents therein
                permanently deleted.
              </p>
              <p>
                Law of Limitations. You agree that regardless of any statute or
                law to the contrary, any claim or cause of action arising out of
                or related to use of the Service or the Terms of Service must be
                filed within one (1) year after such claim or cause of action
                arose or be forever barred.
                <br />
                The section titles in the Terms of Service are for convenience
                only and have no legal or contractual effect.
              </p>
              <p>VIOLATIONS</p>
              <p>
                Please report any violations of the Terms of Services to our
                Grievance Officer/ Support Staff at their email
                hello@thekeysolution.com.
              </p>
              <p>FEES</p>
              <p>
                You acknowledge that we reserve the right to charge for use
                and/or access to some or all aspects of the Site or for
                Services. If you purchase any Services that we offer for a fee,
                either on a one-time or subscription basis ("Paid Services"),
                you agree that {appDomain} (or its authorized service providers)
                may store your payment card information, in accordance with our
                Privacy Policy. You also agree to pay the applicable fees for
                the Paid Services (including, without limitation, periodic fees
                for paid accounts) as they become due plus all related taxes,
                and to reimburse us for all collection costs and interest for
                any overdue amounts. Your obligation to pay fees continues
                through the date you cancel your subscription to the Paid
                Services.{" "}
              </p>
            </div>
            <div>
              <p>
                THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION
                TECHNOLOGY ACT, 2000 AND THE AMENDED PROVISIONS PERTAINING TO
                ELECTRONIC RECORDS IN VARIOUS STATUTES AS AMENDED BY THE
                INFORMATION TECHNOLOGY ACT, 2000. THIS ELECTRONIC RECORD IS
                GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL
                OR DIGITAL SIGNATURES.
              </p>
              <p>
                BY USING THE {appDomain} AT ANY GIVEN TIME YOU AGREE TO OUR
                TERMS AND CONDITIONS.
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }
}
export default legalTerms;
