import React, { Component } from "react";
import Meteor, { createContainer } from "react-web-meteor";
import $ from "jquery";
import "./legal.css";
import { AppTItle, AppURL } from "../../config/config.js";

class userAgreement extends Component {
  componentDidMount() {
    $("#spanHeaderText").text("legal");
  }
  render() {
    let styles = {
      link: {
        maxWidth: "400px",
        padding: "15px"
      }
    };
    $(".backIcon").show();
    $(".backIconMobile").show();
    const appDomain = AppURL;
    const appName = AppTItle;
    return (
      <div className="container-fluid respobsiveMarginTop contactusmaincontent appGradientColor">
        <h3 className="headingTop headingTopMobile appBodyFontColor appBodyFontFamily" />
        <div className="legal-content">
          <div className="legal-header">
            <p>{appName}</p>
            <p>{appDomain}</p>
            <p>USER AGREEMENT</p>
          </div>
          <div>
            <p>
              THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION
              TECHNOLOGY ACT, 2000 AND RULES THERE UNDER AS APPLICABLE AND THE
              AMENDED PROVISIONS PERTAINING TO ELECTRONIC RECORDS IN VARIOUS
              STATUTES AS AMENDED BY THE INFORMATION TECHNOLOGY ACT, 2000. THIS
              ELECTRONIC RECORD IS GENERATED BY A COMPUTER SYSTEM AND DOES NOT
              REQUIRE ANY PHYSICAL OR DIGITAL SIGNATURES.
            </p>
            <p>
              THIS DOCUMENT IS PUBLISHED IN ACCORDANCE WITH THE PROVISIONS OF
              RULE 3 (1) OF THE INFORMATION TECHNOLOGY (INTERMEDIARIES
              GUIDELINES) RULES, 2011 THAT REQUIRE PUBLISHING THE RULES AND
              REGULATIONS, PRIVACY POLICY AND USER AGREEMENT FOR ACCESS OR USAGE
              OF {appDomain}
            </p>
            <p>
              {appName} has taken all reasonable measures to
              ensure the accuracy of the links and profile within {appName}. We invite you to bring to our attention any
              information you believe to be inaccurate. Please respond to
              General Information, along with an explanation of your
              objection.The links and profile that appear on {appDomain} are for
              informational purposes only. Despite our efforts to provide useful
              and accurate information, errors may appear from time to time.
              Before purchasing services you've read about on {appName}, you should confirm with the Agency, Vendor and
              similar entities any information, including the price that is
              important to your purchasing decision. {appName}
              is not responsible for, and does not guarantee the performance of,
              any such or services. USER AGREEMENT
            </p>
            <p>
              a. Your use of a {appName} (including {appDomain}
              (hereinafter referred to as "the Website") and its related sites,
              services and tools} is governed by the following terms and
              conditions as applicable to the {appName} and the
              general principles for other {appDomain} websites of our
              subsidiaries. If you transact on any {appDomain} website other
              than the Home Website, you shall be subject to the policies that
              are applicable to {appDomain} sites for such transaction. This
              User Agreement for the Website shall come into effect on
              19/04/2018 ("User Agreement"). If you reside in India, you are
              contracting with Key Disruptors Private Limited, a company
              incorporated under Companies Act, 2013 with registered office at
              B-502 Sukh Sagar Apartments, Plot no. 12, Sector 9, Dwarka, New
              Delhi, 110075. These terms and conditions constitute your binding
              obligations towards these respective contracting entities
              (hereinafter individually and collectively referred to as
              {appDomain}").b. For the purpose of the User Agreement, Registered
              User / Guest User and wherever the context so require 'You' shall
              mean any natural or legal person who has agreed to become a member
              of the App/ Website by providing Registration Data (as defined
              hereinafter) while registering on the Website as Registered User /
              Guest User using the computer systems of the Website and accepted
              this electronic version / electronic record of the User Agreement
              and has allocated himself a unique identification user name ("User
              ID" and "Password") to become Registered User or have been
              identified as Guest User by providing cell number and email id. c.
              As a new Registered User/ Guest User, this User Agreement shall be
              effective and binding upon your 'acceptance'. 'Acceptance' shall
              mean your affirmative action in clicking on 'check box' and on the
              'continue button' as provided on the registration page or clicking
              on 'Register'/'Sign Up Now' button while transacting as Guest User
              or such other actions that implies your acceptance.. If you do not
              agree or are not willing to be bound by the terms and conditions
              of this User Agreement and {appDomain} Rules and Policies, please
              do not click on the "check box" and on the "continue" button,
              'Register' or "Sign Up Now" button and do not seek to obtain
              access to or otherwise use {appDomain}site.
            </p>
            <p>AMENDMENTS</p>
            <p>
              {appDomain} may amend this User Agreement and/or {appDomain} Rules
              and Policies at any time by posting a revised version on the
              Website. All updates and amendments shall be notified to You via
              Name of the Developed App* App/Website Announcement. The revised
              version will be effective at the time {appDomain} posts it on the
              Website / (Email). In addition, if the revised version of this
              User Agreement includes a Substantial Change, *{appDomain} will
              provide you with 30 days' prior notice of such Substantial
              Change/s by an (Email) or as per the Notification Preferences
              provided by You to {appDomain}. You are also advised to regularly
              check for any amendments or updates to the terms and conditions
              contained in this User Agreement and in {appDomain} Rules and
              Policies. For the purpose of this User Agreement, the term
              "Substantial Change" means a change to the terms of this User
              Agreement that reduces your rights or increases your
              responsibilities. By impliedly or expressly accepting this User
              Agreement, you also accept and agree to be bound by {appDomain}
              Terms of Use and Privacy Policies as provided from time to time in
              the following hyperlinks:
            </p>
            <p>{appDomain}</p>
            <p>MEMBERSHIP ELIGIBILITY</p>
            <p>
              a. Use of the Website is available only to persons who can form
              legally binding contracts under Indian Contract Act, 1872. Persons
              who are "incompetent to contract" within the meaning of the Indian
              Contract Act, 1872 including minors, un-discharged insolvents etc.
              are not eligible to use the Website. If you are a minor i.e. under
              the age of 18 years, you shall not register as a member of the
              Website and shall not interact with other parties on the Website.
              As a minor if you wish to interact with other parties on the
              Website such interaction with other parties can and only should be
              made by your legal guardian or parents who have registered as
              users of the Website or can use the Website as Guest User.{" "}
              {appDomain} reserves the right to terminate your membership and
              refuse to provide you with access to the Website if it is brought
              to {appDomain} notice or if it is discovered that you are under
              the age of 18 years.
            </p>
            <p>YOUR ACCOUNT AND REGISTRATION OBLIGATIONS</p>
            <p>
              a. If you use the Website as a Registered User, you are
              responsible for maintaining the confidentiality of your User ID
              and Password. If you use the Website as a Guest User you are
              responsible for maintaining the confidentiality of your email ID
              and cell number and for restricting access to your computer,
              computer system and computer network, and you are responsible for
              all activities that occur under your User ID and Password, email
              id and cell number as the case may be. Also as a Guest User, you
              shall ensure the physical security and possession of your cell
              phone. You agree, inter alia, to: i. Always provide true,
              accurate, current and complete information about yourself as
              prompted by {appDomain} registration form or provided by You as
              Guest User by the concerned entity using our services (such
              information being the "Registration Data") ii. You must not
              include any of your contact details such as email addresses etc.
              in your User ID while registering as Registered User; and iii.
              Maintain and promptly update the Registration Data to keep it
              true, accurate, current and complete. If you provide any
              information that is untrue, inaccurate, not current or incomplete
              or {appDomain} has reasonable grounds to suspect that such
              information is untrue, inaccurate, not current or incomplete, or
              not in accordance with the User Agreement, {appDomain} has the
              right to indefinitely suspend or terminate or block access of your
              membership with the Website and refuse to provide you with access
              to the Website.
            </p>
            <p>ELECTRONIC COMMUNICATIONS</p>
            <p>
              a. When You use the Website or send emails or other data,
              information or communication to {appDomain}, you agree and
              understand that You are communicating with {appDomain} through
              electronic records and You consent to receive communications via
              electronic records from {appDomain} periodically and as and when
              required. {appDomain} will communicate with You by email or
              electronic records on the {appDomain} which will be deemed
              adequate service of notice / electronic record.
            </p>
            <p>FEES AND SERVICES.</p>
            <p>
              a. Membership on the App/Website is both free and paid and is
              optional as to have a free or a paid account. {appDomain} does not
              charge any fee for browsing on the App/Website. In particular,
              {appDomain} may at its sole discretion introduce new services and
              modify some or all of the existing services offered on the
              App/Website. In such an event {appDomain} reserves the right to
              introduce fees for the new services offered or amend/introduce
              fees for existing services, as the case may be. Changes to the
              policies shall be posted on the App/Website and such changes shall
              automatically become effective immediately after they are posted
              on the App/Website. Unless otherwise stated, all fees shall be
              quoted in Indian Rupees and be payable to Key Disruptors Private
              Limited within such time as specified in the invoice. You shall be
              solely responsible for compliance of all applicable laws including
              those in India for making payments to Key Disruptors Private
              Limited. Your payment to Key Disruptors Private Limited with full
              compliance of all applicable laws shall be sufficient to discharge
              you from your obligations towards payments under these invoices.b.
              Taxes: You are responsible for paying all fees associated with the
              use of the Website and you agree to bear any and all applicable
              taxes, charges, cesses etc. levied thereon. c. Non payment:
              {appDomain} reserves the right to issue a warning, temporarily
              /indefinitely suspend or terminate your membership of the
              App/Website and refuse to provide you with access to the Website
              in case of non-payment of fees by you to {appName}, www.thekeysolution.in also reserves the right to take legal
              action in case of non-payment of fees by you to {appDomain}.
            </p>
            <p>USE OF THE APP/ WEBSITE</p>
            <p>
              You understand and agree that {appDomain} and the Website merely
              provides hosting services to its Registered and Guest Users and
              persons browsing / visiting the Website. All services advertised /
              listed and the contents therein are advertised and listed by
              Registered and Guest Users and are third party generated contents.
              {appDomain}neither originates nor initiates the transmission nor
              select the sender and receiver of the transmission nor selects nor
              modify the information contained in the transmission. {appDomain}
              has no control over the third party generated contents or its
              disbursement method or kind of usage thereto. You agree, undertake
              and confirm that your use of the Website shall be strictly
              governed by the following binding principles:
            </p>
            <p>
              "Your Information" is defined as any information you provide to us
              or other users of the Website ("Users") in the registration (as
              Registered User or as Guest User), in the feedback area or through
              any e-mail feature. You are solely responsible for Your
              Information, and we act only as a passive conduit for your online
              distribution and publication of Your Information. Your Information
              (or any items listed): Please note that in accordance with the
              Information Technology (Intermediaries guidelines) Rules 2011 in
              case of non-compliance with rules and regulations, user agreement
              and privacy policy for access or usage of intermediary computer
              resource, the Intermediary has the right to immediately terminate
              the access or usage rights of the users to the computer resource
              of Intermediary and remove non-compliant information.iii. You
              shall not host, display, upload, modify, publish, transmit, update
              or share any information or share/list(s) any information or
              services that: 1. belongs to another person and to which You does
              not have any right to; 2. is grossly harmful, harassing,
              blasphemous, defamatory, obscene, pornographic, pedophilic,
              libelous, invasive of another's privacy, hateful, or racially,
              ethnically objectionable, disparaging, relating or encouraging
              money laundering or gambling, or otherwise unlawful in any manner
              whatever; or unlawfully threatening or unlawfully harassing
              including but not limited to "indecent representation of women"
              within the meaning of the Indecent Representation of Women
              (Prohibition) Act, 1986; 3. Harm minors in any way; 4. infringes
              any patent, trademark, copyright or other proprietary rights or
              third party's trade secrets or rights of publicity or privacy or
              shall not be fraudulent or involve the sale of counterfeit or
              stolen items; 5. violates any law for the time being in force; 6.
              deceives or misleads the addressee/ users about the origin of such
              messages or communicates any information which is grossly
              offensive or menacing in nature; 7. impersonate another person; 8.
              contains software viruses or any other computer code, files or
              programs designed to interrupt, destroy or limit the functionality
              of any computer resource; or contains any Trojan horses, worms,
              time bombs, cancel bots, Easter eggs or other computer programming
              routines that may damage, detrimentally interfere with, diminish
              value of, surreptitiously intercept or expropriate any system,
              data or personal information; 9. threatens the unity, integrity,
              defence, security or sovereignty of India, friendly relations with
              foreign states, or public order or causes incitement to the
              commission of any cognizable offence or prevents investigation of
              any offence or is insulting any other nation. 10. shall not be
              false, inaccurate or misleading; 11. shall not, directly or
              indirectly, offer, attempt to offer, trade or attempt to trade in
              any item, the dealing of which is prohibited or restricted in any
              manner under the provisions of any applicable law, rule,
              regulation or guideline for the time being in force. 12. shall not
              create liability for us or cause us to lose (in whole or in part)
              the services of our ISPs or other suppliers; and 13. shall not
              link directly or indirectly to or include descriptions of items,
              goods or services that: a. are prohibited under the User Agreement
              or any other applicable law for the time being in force including
              but not limited to the Drugs and Magic Remedies (Objectionable
              Advertisements) Act, 1954, the Indian Penal Code, 1860,
              Information Technology Act 2000 as amended time to time and rules
              there under;c. Solely to enable {appDomain} to use the information
              you supply us with, so that we are not violating any rights you
              might have in Your Information, you agree to grant us a
              non-exclusive, worldwide, perpetual, irrevocable, royalty-free,
              sub-licensable (through multiple tiers) right to exercise the
              copyright, publicity, and database rights (but no other rights)
              you have in Your Information, in any media now known or not
              currently known, with respect to Your Information.
              {appDomain} will only use Your Information in accordance with the
              User Agreement and {appDomain}'s Privacy Policy. d. In the event
              that any transaction or attempted transaction relating to any
              service which is violative of this User Agreement or applicable
              law comes to your knowledge, you shall take all steps to inform
              {appDomain}of the same. You shall not, either alone or in
              conjunction with other Users, manipulate or attempt to manipulate
              the prices of any services being sold or purchased on the Website.
              f. You shall at all times ensure full compliance with the
              applicable provisions of the Information Technology Act, 2000 and
              rules thereunder as applicable and as amended from time to time
              and also all applicable Domestic laws, rules and regulations
              (including the provisions of any applicable Exchange Control Laws
              or Regulations in Force) and International Laws, Foreign Exchange
              Laws, Statutes, Ordinances and Regulations (including, but not
              limited to Sales Tax/ VAT, GST, Income Tax, Central Excise, Custom
              Duty, Local Levies) regarding your use of our service and your
              listing, purchase, solicitation of offers to purchase, and sale of
              services. You shall not engage in any service, which is prohibited
              by the provisions of any applicable law including exchange control
              laws or regulations for the time being in force. g. From time to
              time, you shall be responsible for providing information relating
              to the services proposed to be sold, used or sought by any third
              part, agency or any other person. In this connection, you
              undertake that all such information shall be accurate in all
              respects. You shall not exaggerate or over emphasize the Service
              specifics of such items or services so as to mislead other Users
              in any manner. h. You shall not attempt to or circumvent or
              manipulate our Fee structure, the billing process or Fees owed to
              {appDomain} and incorporated by way of reference in this
              Agreement.
            </p>
            <p>INTERMEDIARY</p>
            <p>
              a. Platform for Communication of the APP/Website is only a
              platform where Users may meet and interact with one agency,
              seller, entities and another's for their services. {appDomain} is
              not and cannot be a party to or control in any manner any
              transaction between two Users of the Website. Consequently: i. All
              commercial / contractual terms are offered by and agreed to
              between the parties alone. The commercial / contractual terms
              include without limitation price, payment methods, payment terms,
              date, period and mode of delivery related to services. {appDomain}
              does not have any control or determines or advises or in any way
              involves itself in the offering or acceptance of such commercial /
              contractual terms between the parties. ii. {appDomain} is not
              responsible for any non-performance or breach of any contract
              entered into between Users (includes Registered User or Guest
              User). {appDomain} cannot and does not guarantee that the
              concerned Users will perform the services concluded on the
              Website. {appDomain} shall not and is not required to mediate or
              resolve any dispute or disagreement between Users. iii.
              {appDomain} does not make any representation or Warranty as to the
              services proposed to be sold or offered to be sold or purchased on
              the Website. In particular, {appDomain} does not implicitly or
              explicitly support or endorse the sale or purchase of any services
              on the Website. {appDomain} accepts no liability for any errors or
              omissions, whether on behalf of itself or third parties. iv.
              {appDomain} does not at any point of time during any transaction
              between the parties on Website come into or takes possession of
              any of the services offered by any User nor does it at any point
              gain title to or have any rights or claims over the services
              offered by the parties. v. The Website is only a venue through
              which Users can reach a larger base to buy and sell services.
              {appDomain} is only providing a platform for communication and it
              is agreed that the contract for sale of any of the services shall
              be a strictly bipartite contract between the parties or the Users
              {appDomain} is not responsible for unsatisfactory or delayed
              performance of services or damages or delays. vi. You shall
              independently agree upon the manner and terms and conditions of
              delivery, payment, insurance etc. with the other Users that you
              transact with. vii. You release and indemnify {appDomain}/ and/or
              any of its officers and representatives from any cost, damage,
              liability or other consequence of any of the actions of the Users
              of the Website and specifically waive any claims that you may have
              in this behalf under any applicable law. Notwithstanding its
              reasonable efforts in that behalf, {appDomain} cannot control the
              information provided by other Users which is made available on the
              Website. You may find other User's information to be offensive,
              harmful, inaccurate, or deceptive. Please use caution and practice
              safe surfing when using the Website. Please note that there may be
              risks in dealing with foreign nationals, underage persons or
              people acting under false pretense.
            </p>
            <p>PRIVACY</p>
            <p>
              We do not sell or rent your personal information to third parties
              for their marketing purposes without your explicit consent and we
              only use your information as described in the Privacy Policy. We
              view protection of users' privacy as a very important community
              principle. We understand clearly that you and Your Personal
              Information is one of our most important assets. We store and
              process Your Information on computers located in India that are
              protected by physical as well as reasonable technological security
              measures and procedures in accordance with Information Technology
              Act 2000 and rules there under. We use third parties to verify and
              certify our privacy principles. If you object to your Information
              being transferred or used in this way, please do not use the
              Website of {appDomain}.
            </p>
            <p>YOUR CONSENT</p>
            <p>
              By using the Site and/ or by providing your information, you
              consent to the collection and use of the information you disclose
              on the Site by {appDomain} in accordance with {appDomain} Privacy
              Policy.
            </p>
            <p>LIMITATION OF LIABILITY</p>
            <p>
              a. In no event shall {appDomain} or its suppliers, affiliates and
              service providers be liable for any direct, indirect, incidental,
              special, incidental, consequential or exemplary damages, including
              but not limited to, damages for loss of profits, goodwill, use,
              data or other intangible losses arising out of or in connection
              with the App/Website, its services or this agreement (however
              arising, including negligence). b. {appDomain} 's liability in any
              circumstance is limited to the amount of fees, if any, paid by You
              to {appDomain}. {appDomain}, its associates, affiliates and
              service providers and technology partners make no representations
              or Warranties about the accuracy, reliability, completeness,
              and/or timeliness of any content, information, software, text,
              graphics, links or communications provided on or through the use
              of the App/Website or that the operation of the App/Website will
              be error free and/or uninterrupted. Consequently, {appDomain}
              assumes no liability whatsoever for any monetary or other damage
              suffered by you on account of: i. The delay, failure,
              interruption, or corruption of any data or other information
              transmitted in connection with use of the App/Website; ii. Any
              interruption or errors in the operation of the App/Website. You
              expressly understand and agree that shall not be liable for any
              direct, indirect, incidental, special, consequential or exemplary
              damages, including but not limited to, damages for loss of
              profits, goodwill, use, data or other intangible losses (even if
              {appDomain} has been advised of the possibility of such damages).
            </p>
            <p>INDEMNITY</p>
            <p>
              a. You shall indemnify and hold harmless {appDomain} and (as
              applicable) {appDomain}'s parent, subsidiaries, affiliates,
              third-parties and their respective officers, directors, agents,
              and employees, from any claim or demand, or actions including
              reasonable attorneys' fees, made by any third party or penalty
              imposed due to or arising out of your breach of the User
              Agreement, *{appDomain} Rules and Policies or the documents they
              incorporates by reference, or your violation of any law, rules or
              regulations or the rights of a third party.
            </p>
            <p>GENERAL</p>
            <p>
              a. None of the provisions of the User Agreement shall be deemed to
              constitute a partnership or agency between You {appDomain} and you
              shall have no authority to bind {appDomain} in any manner
              whatsoever. b. Except as explicitly stated otherwise, any notices
              shall be given by postal mail on behalf of {appDomain} to Key
              Disruptors Private Limited, Attn: Grievance Officer, Legal
              Department, at at B-502 Sukh Sagar Apartments, Plot no. 12, Sector
              9, Dwarka, New Delhi, 110075 (in the case of {appDomain}) or to
              the email address you provide to us during the registration
              process (in your case). Notice shall be deemed given 24 hours
              after email is sent, unless the sending party is notified that the
              email address is invalid. Alternatively, we may give you notice by
              certified mail, postage prepaid and return receipt requested, to
              the address provided to us during the registration process. In
              such case, notice shall be deemed given 3 days after the date of
              mailing. c. If any clause of the User Agreement shall be deemed
              invalid, void or for any reason unenforceable, such clause shall
              be deemed severable and shall not affect the validity and
              enforceability of the remaining clauses of the User Agreement. d.
              This Agreement sets forth the entire understanding and agreement
              between You and {appDomain} with respect to the subject matter
              hereof. e. In *{appDomain}'s sole discretion, {appDomain}may
              transfer its rights and obligations (also known as "assign") under
              this Agreement without your prior express consent, provided that{" "}
              {appDomain} assigns the Agreement on the same terms or terms that
              are no less advantageous to You.
            </p>
            <p>GRIEVANCE OFFICER</p>
            <p>
              In accordance with Information Technology Act 2000 and rules made
              there under, the name and contact details of the Grievance Officer
              is published on the Website. i. Niranjan Bhami D-40, First Floor,
              Sector 6 Noida, Uttar Pradesh - 201301 Email:
              hello@thekeysolution.com
            </p>
            <p>ARBITRATION</p>
            <p>
              If any dispute arises between You and {appDomain} during your use
              of the App/Website thereafter, in connection with the validity,
              interpretation, implementation or alleged breach of any provision
              of the User Agreement or the documents they incorporate by
              reference, the dispute shall be referred to a sole Arbitrator who
              shall be an independent and neutral third party identified by
              {appDomain}. The place of arbitration shall be at New Delhi. The
              Arbitration &amp; Conciliation Act, 1996, shall govern the
              arbitration proceedings. The arbitration proceedings shall be in
              the English language.
            </p>
            <p>GOVERNING LAW</p>
            <p>
              The User Agreement or the documents they incorporate by reference
              shall be governed and construed in accordance with the laws of
              India.
            </p>
            <p>
              THIS DOCUMENT IS AN ELECTRONIC RECORD IN TERMS OF INFORMATION
              TECHNOLOGY ACT, 2000 AND THE AMENDED PROVISIONS PERTAINING TO
              ELECTRONIC RECORDS IN VARIOUS STATUTES AS AMENDED BY THE
              INFORMATION TECHNOLOGY ACT, 2000. THIS ELECTRONIC RECORD IS
              GENERATED BY A COMPUTER SYSTEM AND DOES NOT REQUIRE ANY PHYSICAL
              OR DIGITAL SIGNATURES.
            </p>
            <p>
              BY USING THE {appDomain} AT ANY GIVEN TIME YOU AGREE TO OUR TERMS
              AND CONDITIONS.
            </p>
          </div>
        </div>
      </div>
    );
  }
}
export default userAgreement;
